Autotool the project
Closes issue #6:

  6 - Autotool the project

  https://github.com/ChrisCummins/pat/issues/6

Closes issue #12:

  12 - Make pat multi-user

  This involves separating the shared program files from the per-user
  data, such as:

  /usr/local/bin/pat
  /usr/local/share/pat/pat.py
  /home/bob/.patrc
  /home/bob/pat/cache
  /home/bob/pat/lock

  This feature depends on issue #6 and replaces issue #10.

  https://github.com/ChrisCummins/pat/issues/12

diff --git a/pat.sh.in b/pat.sh.in
--- a/pat.sh.in
+++ b/pat.sh.in
@@ -80,8 +80,8 @@ log() {
 }
 
 test -n "$PAT_DEBUG" && set -x
-PATRC=~/.config/patrc
-PAT="$HOME/.local/share/pat/pat.py"
+PATRC="@PATRC@"
+PAT="@PAT_PY@"
 
 # Parse non-functional arguments first.
 for arg in $@; do
@@ -104,10 +104,10 @@ if [ ! -f $PAT ]; then
 fi
 
 if [ -f $PATRC ]; then
-    . $PATRC
+    . "$PATRC"
 else
-    echo "missing environment file '$PATRC'!"
-    exit 1
+    echo "warning: configuration file '@PATRC@' not found, using defaults" >&2
+    . "@DEFAULT_PATRC@"
 fi
 
 if [ ! -d $PAT_WORKING_DIR ]; then
